apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: darkphusion-com-tls
spec:
  secretName: darkphusion-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: darkphusion.com
  dnsNames:
    - darkphusion.com
    - www.darkphusion.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - darkphusion.com
          - www.darkphusion.com